// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CozyCare.IdentityService.Domain.Entities;

[Index("statusName", Name = "UQ__AccountS__6A50C21291DAFC7D", IsUnique = true)]
public partial class AccountStatus
{
    [Key]
    public int statusId { get; set; }

    [Required]
    [StringLength(50)]
    public string statusName { get; set; }

    [InverseProperty("status")]
    public virtual ICollection<Account> Accounts { get; set; } = new List<Account>();
}