// <auto-generated />
using System;
using CozyCare.BookingService.Infrastructure.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CozyCare.BookingService.Migrations
{
    [DbContext(typeof(CozyCareBookingDbContext))]
    [Migration("20250706054627_AddAddressToBooking")]
    partial class AddAddressToBooking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CozyCare.BookingService.Domain.Entities.Booking", b =>
                {
                    b.Property<int>("bookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("bookingId"));

                    b.Property<string>("Address")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime?>("bookingDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("bookingNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("bookingStatusId")
                        .HasColumnType("int");

                    b.Property<int>("customerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("deadline")
                        .HasColumnType("datetime");

                    b.Property<string>("notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("paymentStatusId")
                        .HasColumnType("int");

                    b.Property<string>("promotionCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("totalAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("bookingId")
                        .HasName("PK__Bookings__C6D03BCDEB934A8C");

                    b.HasIndex("bookingStatusId");

                    b.HasIndex(new[] { "bookingNumber" }, "UQ__Bookings__CB36BB4D2E7005E0")
                        .IsUnique();

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("CozyCare.BookingService.Domain.Entities.BookingDetail", b =>
                {
                    b.Property<int>("detailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("detailId"));

                    b.Property<int>("bookingId")
                        .HasColumnType("int");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("scheduleDatetime")
                        .HasColumnType("datetime");

                    b.Property<int>("serviceId")
                        .HasColumnType("int");

                    b.Property<decimal>("unitPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("detailId")
                        .HasName("PK__BookingD__8307785923E65211");

                    b.HasIndex("bookingId");

                    b.ToTable("BookingDetails");
                });

            modelBuilder.Entity("CozyCare.BookingService.Domain.Entities.BookingStatus", b =>
                {
                    b.Property<int>("statusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("statusId"));

                    b.Property<string>("statusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("statusId")
                        .HasName("PK__BookingS__36257A18274DACF8");

                    b.HasIndex(new[] { "statusName" }, "UQ__BookingS__6A50C21251788D40")
                        .IsUnique();

                    b.ToTable("BookingStatuses");
                });

            modelBuilder.Entity("CozyCare.BookingService.Domain.Entities.Booking", b =>
                {
                    b.HasOne("CozyCare.BookingService.Domain.Entities.BookingStatus", "bookingStatus")
                        .WithMany("Bookings")
                        .HasForeignKey("bookingStatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Bookings_Status");

                    b.Navigation("bookingStatus");
                });

            modelBuilder.Entity("CozyCare.BookingService.Domain.Entities.BookingDetail", b =>
                {
                    b.HasOne("CozyCare.BookingService.Domain.Entities.Booking", "booking")
                        .WithMany("BookingDetails")
                        .HasForeignKey("bookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Details_Bookings");

                    b.Navigation("booking");
                });

            modelBuilder.Entity("CozyCare.BookingService.Domain.Entities.Booking", b =>
                {
                    b.Navigation("BookingDetails");
                });

            modelBuilder.Entity("CozyCare.BookingService.Domain.Entities.BookingStatus", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
