// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CozyCare.PaymentService.Domain.Entities;

public partial class Payment
{
    [Key]
    public int paymentId { get; set; }

    public int userId { get; set; }
    public int bookingId { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal amount { get; set; }

    [Required]
    [StringLength(50)]
    public string paymentMethod { get; set; }

    public int statusId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? paymentDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? createdDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? updatedDate { get; set; }

    [StringLength(500)]
    public string notes { get; set; }

    [StringLength(100)]
    public string momoOrderId { get; set; }

    [ForeignKey("statusId")]
    [InverseProperty("Payments")]
    public virtual PaymentStatus status { get; set; }
}