// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using CozyCare.BookingService.Domain.Entities;
using Microsoft.EntityFrameworkCore;

namespace CozyCare.BookingService.Infrastructure.DBContext;

public partial class CozyCareBookingDbContext : DbContext
{
    public CozyCareBookingDbContext()
    {
    }

    public CozyCareBookingDbContext(DbContextOptions<CozyCareBookingDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Booking> Bookings { get; set; }

    public virtual DbSet<BookingDetail> BookingDetails { get; set; }

    public virtual DbSet<BookingStatus> BookingStatuses { get; set; }

    public static string GetConnectionString(string connectionStringName)
    {
        var config = new ConfigurationBuilder()
            .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
            .AddJsonFile("appsettings.json")
            .Build();

        string connectionString = config.GetConnectionString(connectionStringName);
        return connectionString;
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(GetConnectionString("DefaultConnection"))
        .UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);

    //    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    //#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
    //        => optionsBuilder.UseSqlServer("Data Source=LEGION\\SQLEXPRESS;Initial Catalog=CozyCare.BookingDb;Persist Security Info=True;User ID=sa;Password=1234567890;Encrypt=False");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Booking>(entity =>
        {
            entity.HasKey(e => e.bookingId).HasName("PK__Bookings__C6D03BCDEB934A8C");

            entity.Property(e => e.bookingDate).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.bookingStatus).WithMany(p => p.Bookings)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Bookings_Status");
        });

        modelBuilder.Entity<BookingDetail>(entity =>
        {
            entity.HasKey(e => e.detailId).HasName("PK__BookingD__8307785923E65211");

            entity.HasOne(d => d.booking).WithMany(p => p.BookingDetails).HasConstraintName("FK_Details_Bookings");
        });

        modelBuilder.Entity<BookingStatus>(entity =>
        {
            entity.HasKey(e => e.statusId).HasName("PK__BookingS__36257A18274DACF8");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}