// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CozyCare.CatalogService.Domain.Entities;

public partial class ServiceDetail
{
    [Key]
    public int serviceDetailId { get; set; }

    public int serviceId { get; set; }

    [Required]
    [StringLength(255)]
    public string optionName { get; set; }

    [Required]
    [StringLength(50)]
    public string optionType { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal basePrice { get; set; }

    [Required]
    [StringLength(50)]
    public string unit { get; set; }

    public int duration { get; set; }

    [StringLength(1000)]
    public string description { get; set; }

    public bool? isActive { get; set; }

    [ForeignKey("serviceId")]
    [InverseProperty("ServiceDetails")]
    public virtual Service service { get; set; }
}