// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CozyCare.JobService.Domain.Entities;

public partial class TaskClaim
{
    [Key]
    public int claimId { get; set; }

    public int detailId { get; set; }

    public int housekeeperId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? claimDate { get; set; }

    public int statusId { get; set; }

    [StringLength(500)]
    public string note { get; set; }

    [ForeignKey("statusId")]
    [InverseProperty("TaskClaims")]
    public virtual TaskClaimStatus status { get; set; }
}