// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CozyCare.JobService.Domain.Entities;

[Index("statusName", Name = "UQ__TaskClai__6A50C21240C6275E", IsUnique = true)]
public partial class TaskClaimStatus
{
    [Key]
    public int statusId { get; set; }

    [Required]
    [StringLength(50)]
    public string statusName { get; set; }

    [InverseProperty("status")]
    public virtual ICollection<TaskClaim> TaskClaims { get; set; } = new List<TaskClaim>();
}