// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using CozyCare.CatalogService.Domain.Entities;
using Microsoft.EntityFrameworkCore;

namespace CozyCare.CatalogService.Infrastructure.DBContext;

public partial class CozyCareCatalogDbContext : DbContext
{
    public CozyCareCatalogDbContext()
    {
    }

    public CozyCareCatalogDbContext(DbContextOptions<CozyCareCatalogDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<Service> Services { get; set; }

    public virtual DbSet<ServiceDetail> ServiceDetails { get; set; }

    public static string GetConnectionString(string connectionStringName)
    {
        var config = new ConfigurationBuilder()
            .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
            .AddJsonFile("appsettings.json")
            .Build();

        string connectionString = config.GetConnectionString(connectionStringName);
        return connectionString;
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(GetConnectionString("DefaultConnection"))
        .UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);

    //    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    //#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
    //        => optionsBuilder.UseSqlServer("Data Source=LEGION\\SQLEXPRESS;Initial Catalog=CozyCare.CatalogDb;Persist Security Info=True;User ID=sa;Password=1234567890;Encrypt=False");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Category>(entity =>
        {
            entity.HasKey(e => e.categoryId).HasName("PK__Categori__23CAF1D800231B24");

            entity.Property(e => e.createdDate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.isActive).HasDefaultValue(true);
        });

        modelBuilder.Entity<Service>(entity =>
        {
            entity.HasKey(e => e.serviceId).HasName("PK__Services__455070DFCAA214DD");

            entity.Property(e => e.createdDate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.isActive).HasDefaultValue(true);

            entity.HasOne(d => d.category).WithMany(p => p.Services)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Services_Categories");
        });

        modelBuilder.Entity<ServiceDetail>(entity =>
        {
            entity.HasKey(e => e.serviceDetailId).HasName("PK__ServiceD__DF439C591BD1F000");

            entity.Property(e => e.isActive).HasDefaultValue(true);

            entity.HasOne(d => d.service).WithMany(p => p.ServiceDetails)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ServiceDetails_Services");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}