// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CozyCare.DAL.Entities;

[Index("email", Name = "UQ__Accounts__AB6E616441D52327", IsUnique = true)]
public partial class Account
{
    [Key]
    public int accountId { get; set; }

    [Required]
    [StringLength(255)]
    public string email { get; set; }

    [Required]
    [StringLength(255)]
    public string password { get; set; }

    [StringLength(255)]
    public string address { get; set; }

    [StringLength(20)]
    public string phone { get; set; }

    [StringLength(255)]
    public string fullName { get; set; }

    [StringLength(255)]
    public string avatar { get; set; }

    public int roleId { get; set; }

    public int statusId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? createdDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? updatedDate { get; set; }

    public int? createdBy { get; set; }

    public int? updatedBy { get; set; }

    [InverseProperty("customer")]
    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    [InverseProperty("housekeeper")]
    public virtual ICollection<HousekeeperAvailability> HousekeeperAvailabilities { get; set; } = new List<HousekeeperAvailability>();

    [InverseProperty("account")]
    public virtual ICollection<Housekeeper> Housekeepers { get; set; } = new List<Housekeeper>();

    [InverseProperty("createdByNavigation")]
    public virtual ICollection<Account> InversecreatedByNavigation { get; set; } = new List<Account>();

    [InverseProperty("updatedByNavigation")]
    public virtual ICollection<Account> InverseupdatedByNavigation { get; set; } = new List<Account>();

    [InverseProperty("housekeeper")]
    public virtual ICollection<Report> Reports { get; set; } = new List<Report>();

    [InverseProperty("customer")]
    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    [InverseProperty("housekeeper")]
    public virtual ICollection<ScheduleAssignment> ScheduleAssignments { get; set; } = new List<ScheduleAssignment>();

    [ForeignKey("createdBy")]
    [InverseProperty("InversecreatedByNavigation")]
    public virtual Account createdByNavigation { get; set; }

    [ForeignKey("roleId")]
    [InverseProperty("Accounts")]
    public virtual Role role { get; set; }

    [ForeignKey("statusId")]
    [InverseProperty("Accounts")]
    public virtual AccountStatus status { get; set; }

    [ForeignKey("updatedBy")]
    [InverseProperty("InverseupdatedByNavigation")]
    public virtual Account updatedByNavigation { get; set; }
}