// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CozyCare.DAL.Entities;

[Index("statusName", Name = "UQ__Assignme__6A50C212EE1079C7", IsUnique = true)]
public partial class AssignmentStatus
{
    [Key]
    public int statusId { get; set; }

    [Required]
    [StringLength(50)]
    public string statusName { get; set; }

    [InverseProperty("status")]
    public virtual ICollection<ScheduleAssignment> ScheduleAssignments { get; set; } = new List<ScheduleAssignment>();
}