// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CozyCare.DAL.Entities;

public partial class BookingDetail
{
    [Key]
    public int detailId { get; set; }

    public int bookingId { get; set; }

    public int serviceId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime scheduleDatetime { get; set; }

    public int quantity { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal unitPrice { get; set; }

    [InverseProperty("detail")]
    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    [InverseProperty("detail")]
    public virtual ICollection<ScheduleAssignment> ScheduleAssignments { get; set; } = new List<ScheduleAssignment>();

    [ForeignKey("bookingId")]
    [InverseProperty("BookingDetails")]
    public virtual Booking booking { get; set; }

    [ForeignKey("serviceId")]
    [InverseProperty("BookingDetails")]
    public virtual Service service { get; set; }
}