// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CozyCare.DAL.Entities;

[Index("bookingNumber", Name = "UQ__Bookings__CB36BB4D7873AA48", IsUnique = true)]
public partial class Booking
{
    [Key]
    public int bookingId { get; set; }

    [Required]
    [StringLength(50)]
    public string bookingNumber { get; set; }

    public int customerId { get; set; }

    [StringLength(50)]
    public string promotionCode { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? bookingDate { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal totalAmount { get; set; }

    [StringLength(500)]
    public string notes { get; set; }

    public int bookingStatusId { get; set; }

    public int paymentStatusId { get; set; }

    [InverseProperty("booking")]
    public virtual ICollection<BookingDetail> BookingDetails { get; set; } = new List<BookingDetail>();

    [InverseProperty("booking")]
    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    [ForeignKey("bookingStatusId")]
    [InverseProperty("Bookings")]
    public virtual BookingStatus bookingStatus { get; set; }

    [ForeignKey("customerId")]
    [InverseProperty("Bookings")]
    public virtual Account customer { get; set; }

    [ForeignKey("paymentStatusId")]
    [InverseProperty("Bookings")]
    public virtual PaymentStatus paymentStatus { get; set; }

    [ForeignKey("promotionCode")]
    [InverseProperty("Bookings")]
    public virtual Promotion promotionCodeNavigation { get; set; }
}