// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CozyCare.DAL.Entities;

public partial class Housekeeper
{
    [Key]
    public int housekeeperId { get; set; }

    public int accountId { get; set; }

    public double? rating { get; set; }

    public int? experience { get; set; }

    [ForeignKey("accountId")]
    [InverseProperty("Housekeepers")]
    public virtual Account account { get; set; }
}