// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CozyCare.DAL.Entities;

[Table("HousekeeperAvailability")]
public partial class HousekeeperAvailability
{
    [Key]
    public int availabilityId { get; set; }

    public int housekeeperId { get; set; }

    public DateOnly availableDate { get; set; }

    public TimeOnly startTime { get; set; }

    public TimeOnly endTime { get; set; }

    [ForeignKey("housekeeperId")]
    [InverseProperty("HousekeeperAvailabilities")]
    public virtual Account housekeeper { get; set; }
}