// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CozyCare.DAL.Entities;

public partial class Promotion
{
    [Key]
    [StringLength(50)]
    public string code { get; set; }

    [Required]
    [StringLength(20)]
    public string discountType { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? discountAmount { get; set; }

    public double? discountPercent { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime startDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime endDate { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? minOrderAmount { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? maxDiscountAmount { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? createdDate { get; set; }

    [InverseProperty("promotionCodeNavigation")]
    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();
}