// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CozyCare.DAL.Entities;

public partial class Report
{
    [Key]
    public int recordId { get; set; }

    public int housekeeperId { get; set; }

    public int assignId { get; set; }

    public DateOnly workDate { get; set; }

    public TimeOnly startTime { get; set; }

    public TimeOnly endTime { get; set; }

    public double totalHours { get; set; }

    [Required]
    [StringLength(50)]
    public string taskStatus { get; set; }

    [ForeignKey("assignId")]
    [InverseProperty("Reports")]
    public virtual ScheduleAssignment assign { get; set; }

    [ForeignKey("housekeeperId")]
    [InverseProperty("Reports")]
    public virtual Account housekeeper { get; set; }
}