// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CozyCare.DAL.Entities;

public partial class Review
{
    [Key]
    public int reviewId { get; set; }

    public int customerId { get; set; }

    public int detailId { get; set; }

    [Required]
    [StringLength(20)]
    public string reviewTarget { get; set; }

    public int? rating { get; set; }

    [StringLength(1000)]
    public string comment { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? reviewDate { get; set; }

    [ForeignKey("customerId")]
    [InverseProperty("Reviews")]
    public virtual Account customer { get; set; }

    [ForeignKey("detailId")]
    [InverseProperty("Reviews")]
    public virtual BookingDetail detail { get; set; }
}