// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CozyCare.DAL.Entities;

public partial class ScheduleAssignment
{
    [Key]
    public int assignmentId { get; set; }

    public int housekeeperId { get; set; }

    public int detailId { get; set; }

    public DateOnly assignDate { get; set; }

    public TimeOnly startTime { get; set; }

    public TimeOnly endTime { get; set; }

    public int statusId { get; set; }

    [StringLength(500)]
    public string notes { get; set; }

    [InverseProperty("assign")]
    public virtual ICollection<Report> Reports { get; set; } = new List<Report>();

    [ForeignKey("detailId")]
    [InverseProperty("ScheduleAssignments")]
    public virtual BookingDetail detail { get; set; }

    [ForeignKey("housekeeperId")]
    [InverseProperty("ScheduleAssignments")]
    public virtual Account housekeeper { get; set; }

    [ForeignKey("statusId")]
    [InverseProperty("ScheduleAssignments")]
    public virtual AssignmentStatus status { get; set; }
}