// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CozyCare.DAL.Entities;

public partial class Service
{
    [Key]
    public int serviceId { get; set; }

    public int categoryId { get; set; }

    [Required]
    [StringLength(255)]
    public string serviceName { get; set; }

    [StringLength(500)]
    public string description { get; set; }

    [StringLength(255)]
    public string image { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal price { get; set; }

    public int duration { get; set; }

    public bool? isActive { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? createdDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? updatedDate { get; set; }

    [InverseProperty("service")]
    public virtual ICollection<BookingDetail> BookingDetails { get; set; } = new List<BookingDetail>();

    [InverseProperty("service")]
    public virtual ICollection<ServiceDetail> ServiceDetails { get; set; } = new List<ServiceDetail>();

    [ForeignKey("categoryId")]
    [InverseProperty("Services")]
    public virtual Category category { get; set; }
}