// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CozyCare.DAL.Entities;

public partial class ServiceDetail
{
    [Key]
    public int serviceDetailId { get; set; }

    public int serviceId { get; set; }

    [Required]
    [StringLength(255)]
    public string OptionName { get; set; }

    [Required]
    [StringLength(50)]
    public string OptionType { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal BasePrice { get; set; }

    [Required]
    [StringLength(50)]
    public string Unit { get; set; }

    public int Duration { get; set; }

    [StringLength(1000)]
    public string Description { get; set; }

    public bool IsActive { get; set; }

    [ForeignKey("serviceId")]
    [InverseProperty("ServiceDetails")]
    public virtual Service service { get; set; }
}