// <auto-generated />
using System;
using CozyCare.CatalogService.Infrastructure.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CozyCare.CatalogService.Migrations
{
    [DbContext(typeof(CozyCareCatalogDbContext))]
    partial class CozyCareCatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CozyCare.CatalogService.Domain.Entities.Category", b =>
                {
                    b.Property<int>("categoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("categoryId"));

                    b.Property<string>("categoryName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("createdDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("image")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("isActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("updatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("categoryId")
                        .HasName("PK__Categori__23CAF1D800231B24");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("CozyCare.CatalogService.Domain.Entities.Service", b =>
                {
                    b.Property<int>("serviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("serviceId"));

                    b.Property<int>("categoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("createdDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("duration")
                        .HasColumnType("int");

                    b.Property<string>("image")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("isActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("serviceName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("updatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("serviceId")
                        .HasName("PK__Services__455070DFCAA214DD");

                    b.HasIndex("categoryId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("CozyCare.CatalogService.Domain.Entities.ServiceDetail", b =>
                {
                    b.Property<int>("serviceDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("serviceDetailId"));

                    b.Property<decimal>("basePrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("duration")
                        .HasColumnType("int");

                    b.Property<bool?>("isActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("optionName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("optionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("serviceId")
                        .HasColumnType("int");

                    b.Property<string>("unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("serviceDetailId")
                        .HasName("PK__ServiceD__DF439C591BD1F000");

                    b.HasIndex("serviceId");

                    b.ToTable("ServiceDetails");
                });

            modelBuilder.Entity("CozyCare.CatalogService.Domain.Entities.Service", b =>
                {
                    b.HasOne("CozyCare.CatalogService.Domain.Entities.Category", "category")
                        .WithMany("Services")
                        .HasForeignKey("categoryId")
                        .IsRequired()
                        .HasConstraintName("FK_Services_Categories");

                    b.Navigation("category");
                });

            modelBuilder.Entity("CozyCare.CatalogService.Domain.Entities.ServiceDetail", b =>
                {
                    b.HasOne("CozyCare.CatalogService.Domain.Entities.Service", "service")
                        .WithMany("ServiceDetails")
                        .HasForeignKey("serviceId")
                        .IsRequired()
                        .HasConstraintName("FK_ServiceDetails_Services");

                    b.Navigation("service");
                });

            modelBuilder.Entity("CozyCare.CatalogService.Domain.Entities.Category", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("CozyCare.CatalogService.Domain.Entities.Service", b =>
                {
                    b.Navigation("ServiceDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
