// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using CozyCare.IdentityService.Domain.Entities;
using Microsoft.EntityFrameworkCore;

namespace CozyCare.IdentityService.Infrastructure.DBContext;

public partial class CozyCareIdentityDbContext : DbContext
{
    public CozyCareIdentityDbContext()
    {
    }

    public CozyCareIdentityDbContext(DbContextOptions<CozyCareIdentityDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Account> Accounts { get; set; }

    public virtual DbSet<AccountStatus> AccountStatuses { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public static string GetConnectionString(string connectionStringName)
    {
        var config = new ConfigurationBuilder()
            .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
            .AddJsonFile("appsettings.json")
            .Build();

        string connectionString = config.GetConnectionString(connectionStringName);
        return connectionString;
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(GetConnectionString("DefaultConnection"))
        .UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);

    //    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    //#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
    //        => optionsBuilder.UseSqlServer("Data Source=LEGION\\SQLEXPRESS;Initial Catalog=CozyCare.IdentityDb;Persist Security Info=True;User ID=sa;Password=1234567890;Encrypt=False");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Account>(entity =>
        {
            entity.HasKey(e => e.accountId).HasName("PK__Accounts__F267251E562754A3");

            entity.Property(e => e.createdDate).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.createdByNavigation).WithMany(p => p.InversecreatedByNavigation).HasConstraintName("FK_Accounts_CreatedBy");

            entity.HasOne(d => d.role).WithMany(p => p.Accounts)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Accounts_Roles");

            entity.HasOne(d => d.status).WithMany(p => p.Accounts)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Accounts_Status");

            entity.HasOne(d => d.updatedByNavigation).WithMany(p => p.InverseupdatedByNavigation).HasConstraintName("FK_Accounts_UpdatedBy");
        });

        modelBuilder.Entity<AccountStatus>(entity =>
        {
            entity.HasKey(e => e.statusId).HasName("PK__AccountS__36257A184AF21423");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.roleId).HasName("PK__Roles__CD98462AA584129C");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}