// <auto-generated />
using System;
using CozyCare.PaymentService.Infrastructure.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CozyCare.PaymentService.Migrations
{
    [DbContext(typeof(CozyCarePaymentDbContext))]
    [Migration("20250709023947_AddMomoOrderIdToPayment")]
    partial class AddMomoOrderIdToPayment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CozyCare.PaymentService.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("paymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("paymentId"));

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("bookingId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("createdDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("momoOrderId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("paymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("paymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("statusId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("updatedDate")
                        .HasColumnType("datetime");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.HasKey("paymentId")
                        .HasName("PK__Payments__A0D9EFC60A080688");

                    b.HasIndex("statusId");

                    b.ToTable("Payments", t =>
                        {
                            t.Property("userId")
                                .HasColumnName("userId1");
                        });
                });

            modelBuilder.Entity("CozyCare.PaymentService.Domain.Entities.PaymentStatus", b =>
                {
                    b.Property<int>("statusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("statusId"));

                    b.Property<string>("statusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("statusId")
                        .HasName("PK__PaymentS__36257A1895B1351F");

                    b.HasIndex(new[] { "statusName" }, "UQ__PaymentS__6A50C212399E5850")
                        .IsUnique();

                    b.ToTable("PaymentStatuses");
                });

            modelBuilder.Entity("CozyCare.PaymentService.Domain.Entities.Promotion", b =>
                {
                    b.Property<string>("code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("createdDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("discountAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<double?>("discountPercent")
                        .HasColumnType("float");

                    b.Property<string>("discountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("endDate")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("maxDiscountAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("minOrderAmount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("datetime");

                    b.HasKey("code")
                        .HasName("PK__Promotio__357D4CF8B09207D5");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("CozyCare.PaymentService.Domain.Entities.Payment", b =>
                {
                    b.HasOne("CozyCare.PaymentService.Domain.Entities.PaymentStatus", "status")
                        .WithMany("Payments")
                        .HasForeignKey("statusId")
                        .IsRequired()
                        .HasConstraintName("FK_Payments_Status");

                    b.Navigation("status");
                });

            modelBuilder.Entity("CozyCare.PaymentService.Domain.Entities.PaymentStatus", b =>
                {
                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
